from ds.registry import Registry


SYMBOLS_TABLE_MAX = 100

SYMBOLS_TABLE: [Registry] = [None] * SYMBOLS_TABLE_MAX
SYMBOLS_TABLE_ITERATOR: int = 0

INIT_DECLARATION_TOKEN: [int] = []
INIT_INSTRUCTION_TOKEN: [int] = []
INIT_FACTOR_TOKEN: [int] = []

ERROR_COUNTER = 0
LANGUAGE_TOKEN_AMOUNT = 50
